version: '3'

services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - '.data/postgres:/var/lib/postgresql/data'
    env_file:
      - 'dev.env'

  api:
    depends_on:
      - 'postgres'
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c './api-entrypoint.sh'
    ports:
      - '3000:3000'
    env_file:
      - 'dev.env'

